update qa.yml and update the admin password in cypress test as well

diff --git a/.github/workflows/qa.yml b/.github/workflows/qa.yml
--- a/.github/workflows/qa.yml
+++ b/.github/workflows/qa.yml
@@ -10,6 +10,10 @@ jobs:
   build-and-test:
     runs-on: ubuntu-latest
 
+    env:
+      RAILS_ENV: development
+      NODE_ENV: development
+
     steps:
 
     - name: Checkout Repository
@@ -43,11 +47,16 @@ jobs:
       run: |
         bundle exec rails db:create
         bundle exec rails db:migrate
+        bundle exec rails db:seed
 
     - name: Start Spree Server
       run: |
-        bundle exec rails server -d -p 3000
-        sleep 20
+        bundle exec rails server -e development -d -p 3000
+        sleep 30
+
+    - name: Verify Server is Running
+      run: |
+        curl --retry 10 --retry-delay 3 --retry-connrefused http://localhost:3000 || (echo "Server failed to start" && exit 1)
 
     # ----------------------------
     # Run Cypress Tests
